server:
  port : 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.123.123.123:3306/go?serverTimezone=GMT%2B8
    username: root
    password: 123123...
  mail:
    host: smtp.163.com
    port: 465
    username: 123123@163.com
    password: 123123
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socket:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            auth: true
  data:
    redis:
      host: 123.123.123.123
      port: 6366
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      database: 2
      password: 123123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.hexadecimal: debug